[project]
name = "ownbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "3.12.8"
dependencies = [
    "aiogram>=3.15.0",
    "aiosqlite>=0.20.0",
    "openpyxl>=3.1.5",
    "sqlalchemy>=2.0.36",
]
