"""TodoistTask modification

Revision ID: 1a102097d7db
Revises: fc173a06d2b9
Create Date: 2024-12-20 09:26:40.445464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a102097d7db'
down_revision: Union[str, None] = 'fc173a06d2b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todoisttask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_item_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('task_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('added_at', sa.TIMESTAMP(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todoisttask', schema=None) as batch_op:
        batch_op.drop_column('added_at')
        batch_op.drop_column('task_id')
        batch_op.drop_column('project_id')
        batch_op.drop_column('task_item_id')

    # ### end Alembic commands ###
