"""init

Revision ID: 29e0ddc87123
Revises: 
Create Date: 2024-12-24 12:08:19.733033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '29e0ddc87123'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usermodel',
    sa.Column('telegram_id', sa.BIGINT(), nullable=False),
    sa.Column('todoist_token', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('indicatorparams',
    sa.Column('indicator_name', sa.String(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.Column('label_name', sa.String(), nullable=True),
    sa.Column('task_name', sa.String(), nullable=True),
    sa.Column('description_literal', sa.String(), nullable=True),
    sa.Column('calc_as_average', sa.Boolean(), nullable=False),
    sa.Column('project_track_based_method', sa.Boolean(), nullable=False),
    sa.Column('description_based_method', sa.Boolean(), nullable=False),
    sa.Column('quantity_based_method', sa.Boolean(), nullable=False),
    sa.Column('file_based_method', sa.Boolean(), nullable=False),
    sa.Column('label_track_based_method', sa.Boolean(), nullable=False),
    sa.Column('task_name_track_based_method', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usermodel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description_literal'),
    sa.UniqueConstraint('user_id', 'indicator_name', name='uq_user_indicator')
    )
    op.create_table('report',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.Enum('FULL', 'INDICATOR', 'GRAPH', name='reporttype'), nullable=False),
    sa.Column('start', sa.TIMESTAMP(), nullable=False),
    sa.Column('end', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usermodel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('scheduletask',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.Enum('REGULAR', 'ONCE', 'DAILY', 'WEEKLY', name='tasktype'), nullable=False),
    sa.Column('schedule', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usermodel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('todoisttask',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_item_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('task', sa.String(), nullable=False),
    sa.Column('project', sa.String(), nullable=True),
    sa.Column('labels', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usermodel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('indicator',
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('indicator_name', sa.String(), nullable=False),
    sa.Column('params', sqlite.JSON(), nullable=True),
    sa.Column('indicator_params_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['indicator_params_id'], ['indicatorparams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usermodel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicator_name'),
    sa.UniqueConstraint('user_id', 'indicator_name', name='uq_user_indicator')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indicator')
    op.drop_table('todoisttask')
    op.drop_table('scheduletask')
    op.drop_table('report')
    op.drop_table('indicatorparams')
    op.drop_table('usermodel')
    # ### end Alembic commands ###
