"""empty message

Revision ID: 2f87409d32a3
Revises: bc9998fc215d
Create Date: 2024-12-26 15:04:34.285951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f87409d32a3'
down_revision: Union[str, None] = 'bc9998fc215d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indicator', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_indicator', type_='unique')
        batch_op.create_unique_constraint('uq_user_indicator_date', ['user_id', 'indicator_name', 'date'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indicator', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_indicator_date', type_='unique')
        batch_op.create_unique_constraint('uq_user_indicator', ['user_id', 'indicator_name', 'date'])

    # ### end Alembic commands ###
