"""empty message

Revision ID: 36e730ce0bd2
Revises: 29e0ddc87123
Create Date: 2024-12-25 15:03:46.863279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36e730ce0bd2'
down_revision: Union[str, None] = '29e0ddc87123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indicatorparams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_read_param', sa.String(), nullable=True))
        batch_op.alter_column('file_based_method',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               nullable=True)
        batch_op.create_unique_constraint('uq_user_description_literal', ['user_id', 'description_literal'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indicatorparams', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_description_literal', type_='unique')
        batch_op.alter_column('file_based_method',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_column('file_read_param')

    # ### end Alembic commands ###
