"""date_fields to TodoistTask and Indicator

Revision ID: 44ec4505cd4c
Revises: b69d3db34520
Create Date: 2024-12-19 16:54:32.411557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44ec4505cd4c'
down_revision: Union[str, None] = 'b69d3db34520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indicator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=False))

    with op.batch_alter_table('todoisttask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.TIMESTAMP(), nullable=False))
        batch_op.drop_column('done_time')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todoisttask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('done_time', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('completed_at')

    with op.batch_alter_table('indicator', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
