"""empty message

Revision ID: b69d3db34520
Revises: deab777fead2
Create Date: 2024-12-19 09:30:49.338418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b69d3db34520'
down_revision: Union[str, None] = 'deab777fead2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usermodel', schema=None) as batch_op:
        batch_op.alter_column('todoist_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('telegram_token')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usermodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_token', sa.VARCHAR(), nullable=False))
        batch_op.alter_column('todoist_token',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
