"""empty message

Revision ID: c63738accf7a
Revises: 0d5ab5037e05
Create Date: 2025-01-14 09:35:14.646326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c63738accf7a'
down_revision: Union[str, None] = '0d5ab5037e05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduletask', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_name_user_id', ['user_id', 'name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduletask', schema=None) as batch_op:
        batch_op.drop_constraint('uq_name_user_id', type_='unique')

    # ### end Alembic commands ###
