"""Recreate indicator table

Revision ID: f2ca8122fe97
Revises: bf680218422d
Create Date: 2024-12-26 15:25:17.114679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2ca8122fe97'
down_revision: Union[str, None] = 'bf680218422d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicator',
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('indicator_name', sa.String(), nullable=False),
    sa.Column('indicator_value', sa.Integer(), nullable=False),
    sa.Column('indicator_params_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['indicator_params_id'], ['indicatorparams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usermodel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'indicator_name', 'date', name='uq_user_indicator_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indicator')
    # ### end Alembic commands ###
