"""TodoistTask correction

Revision ID: fc173a06d2b9
Revises: 44ec4505cd4c
Create Date: 2024-12-19 18:36:06.456481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc173a06d2b9'
down_revision: Union[str, None] = '44ec4505cd4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todoisttask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('labels', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=True))
        batch_op.drop_column('todoist_task')
        batch_op.drop_column('label')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todoisttask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('todoist_task', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('priority')
        batch_op.drop_column('labels')
        batch_op.drop_column('task')

    # ### end Alembic commands ###
